thisdir = class/Mono.ZeroConf
SUBDIRS = 
include ../../build/rules.make

LIBRARY = Mono.ZeroConf.dll
LIB_MCS_FLAGS = -r:System

TEST_MCS_FLAGS = $(LIB_MCS_FLAGS)

EXTRA_DISTFILES = Test/ZeroConfTest.cs

include ../../build/library.make


